export const developers = [
    {
        "developer_id": 1,
        "name": "Alice",
        "email": "Alice@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
      {
        "developer_id": 2,
        "name": "john",
        "email": "john@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
      {
        "developer_id": 3,
        "name": "sherin",
        "email": "sherin@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
      {
        "developer_id": 4,
        "name": "riyas",
        "email": "riyas@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
      {
        "developer_id": 5,
        "name": "shajon",
        "email": "shajon@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
      {
        "developer_id": 6,
        "name": "ravi",
        "email": "ravi@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
      {
        "developer_id": 7,
        "name": "rahul",
        "email": "rahul@company.com",
        "role": "Developer",
        "permissions": ["read", "write"],
        "created" :1742169600,
      },
]